In [1]:
# 평균값

import pandas as pd

In [2]:

df = pd.read_csv("./data/auto-mpg.csv",header=None)


df.columns=[
    "mpg",'cylinder','displacement',"horsepower","weight","acceleration","model year","origin","name"
]
df.head()

,mpg,cylinder,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinder      398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [ ]:
df.mean(numeric_only=True) #숫자만 가져와서 평균값 낸다라는 것.

mpg               23.514573
cylinder           5.454774
displacement     193.425879
weight          2970.424623
acceleration      15.568090
model year        76.010050
origin             1.572864
dtype: float64

In [8]:
round(df["mpg"].mean(),2)

np.float64(23.51)

In [12]:
# 중앙값

df.median(numeric_only=True)
df.mpg.median()

np.float64(23.0)

In [21]:
print(df.max(numeric_only=True))
print("\n")

print(df.min())

df["horsepower"]

mpg               46.6
cylinder           8.0
displacement     455.0
weight          5140.0
acceleration      24.8
model year        82.0
origin             3.0
dtype: float64


mpg                                 9.0
cylinder                              3
displacement                       68.0
horsepower                        100.0
weight                           1613.0
acceleration                        8.0
model year                           70
origin                                1
name            amc ambassador brougham
dtype: object

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393    86.00
394    52.00
395    84.00
396    79.00
397    82.00
Name: horsepower, Length: 398, dtype: str

In [22]:
df.min(numeric_only=True)

mpg                9.0
cylinder           3.0
displacement      68.0
weight          1613.0
acceleration       8.0
model year        70.0
origin             1.0
dtype: float64

In [24]:
df.std(numeric_only=True)

mpg               7.815984
cylinder          1.701004
displacement    104.269838
weight          846.841774
acceleration      2.757689
model year        3.697627
origin            0.802055
dtype: float64

In [26]:
# 상관계수

# DataFrame객체.corr()
# DataFrame객체[열이름의 리스트].corr()

df[["mpg", "weight"]].corr()

             mpg    weight
mpg     1.000000 -0.831741
weight -0.831741  1.000000