In [1]:
# csv 파일로 저장

# DataFrame객체.to_csv("이름")
import pandas as pd


data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
    'algol' : [ "A", "A+", "B"],
    'basic' : [ "C", "B", "B+"],
    'c++' : [ "B+", "C", "C+"],
}

df = pd.DataFrame(data)
df.set_index("name")
df

    name algol basic c++
0  Jerry     A     C  B+
1   Riah    A+     B   C
2   Paul     B    B+  C+

In [2]:
df.to_csv("./data/df_sample.csv")

In [3]:
df

    name algol basic c++
0  Jerry     A     C  B+
1   Riah    A+     B   C
2   Paul     B    B+  C+

In [4]:
df.to_csv("./data/df_sample_no_index.csv", index=False)

In [5]:
# json 파일로 저장

import pandas as pd


data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
    'algol' : [ "A", "A+", "B"],
    'basic' : [ "C", "B", "B+"],
    'c++' : [ "B+", "C", "C+"],
}

df = pd.DataFrame(data)
df = df.set_index("name")
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [6]:
# DataFrame객체.to_json("파일이름")

df.to_json("./data/df_sample.json")

In [7]:
df.to_json("./data/df_sample_split.json", orient="split")

In [8]:
df.to_json("./data/df_sample_records.json",orient="records")

In [9]:
df.to_json("./data/df_sample_index.json", orient="index")

In [10]:
df.to_json("./data/df_sample_columns.json",orient="columns")

In [11]:
df.to_json("./data/df_sample_values.json",orient="values")