In [1]:
import pandas as pd

In [2]:
fruit_names = pd.Series([
    "Apple","Banana","Cherry"
])

fruit_names

0     Apple
1    Banana
2    Cherry
dtype: str

In [4]:
pd.Series([
    "Apple","Banana","Cherry"
], dtype = pd.StringDtype())

0     Apple
1    Banana
2    Cherry
dtype: string

In [7]:
fruit_names.astype("string")

0     Apple
1    Banana
2    Cherry
dtype: string

In [13]:
# 문자열 매서드

import pandas as pd
import numpy as np

ser = pd.Series([
    "Apple_사과","Banana_바나나","Cherry_체리",np.nan
], index = ["First ", " Second", " Thrid", "Fourth"])

ser

ser2 = pd.Series([
    "Apple_사과","Banana_바나나","Cherry_체리",np.nan
], index = ["First ", " Second", " Thrid", "Fourth"], dtype="string")

ser2

First        Apple_사과
 Second    Banana_바나나
 Thrid      Cherry_체리
Fourth           <NA>
dtype: string

In [16]:
print(ser.str.lower())
print(ser.str.upper())
print(ser.str.len())

First        apple_사과
 Second    banana_바나나
 Thrid      cherry_체리
Fourth            NaN
dtype: str
First        APPLE_사과
 Second    BANANA_바나나
 Thrid      CHERRY_체리
Fourth            NaN
dtype: str
First       8.0
 Second    10.0
 Thrid      9.0
Fourth      NaN
dtype: float64

In [17]:
ser

First        Apple_사과
 Second    Banana_바나나
 Thrid      Cherry_체리
Fourth            NaN
dtype: str

In [18]:
result1 = ser.str.split("_")
result1

First        [Apple, 사과]
 Second    [Banana, 바나나]
 Thrid      [Cherry, 체리]
Fourth               NaN
dtype: object

In [19]:
result2 = ser.str.split("_",expand=True)
result2

              0    1
First     Apple   사과
 Second  Banana  바나나
 Thrid   Cherry   체리
Fourth      NaN  NaN

In [21]:
ser.str.split("_").str.get(0)

First       Apple
 Second    Banana
 Thrid     Cherry
Fourth        NaN
dtype: object

In [24]:
# 문자열 매서드

idx = ser.index

print(idx.str.strip())
print(idx)

Index(['First', 'Second', 'Thrid', 'Fourth'], dtype='str')
Index(['First ', ' Second', ' Thrid', 'Fourth'], dtype='str')

In [ ]:
print(ser.str.replace("_",":",regex=False)) #_를 : 으로 바꾼다는것.

First        Apple:사과
 Second    Banana:바나나
 Thrid      Cherry:체리
Fourth            NaN
dtype: str

In [27]:
ser.str.replace("[^a-zA-Z\s]", "", regex=True)

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\wm032\AppData\Local\Temp\ipykernel_7664\3217377679.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  ser.str.replace("[^a-zA-Z\s]", "", regex=True)

First       Apple
 Second    Banana
 Thrid     Cherry
Fourth        NaN
dtype: str

In [ ]:
print(ser.str[0]) #첫글자를 가져옴(인덱싱)

First        A
 Second      B
 Thrid       C
Fourth     NaN
dtype: str

In [29]:
ser.str[0:4]

First      Appl
 Second    Bana
 Thrid     Cher
Fourth      NaN
dtype: str

In [30]:
ser.str.contains("A", na = False)

First       True
 Second    False
 Thrid     False
Fourth     False
dtype: bool

In [31]:
ser.str.contains(r"[A|B][a-z]*")

First       True
 Second     True
 Thrid     False
Fourth     False
dtype: bool

In [32]:
ser.str.fullmatch(r"[A|B][a-z]*")

First      False
 Second    False
 Thrid     False
Fourth     False
dtype: bool

In [33]:
ser3 = pd.Series([
    "a1","b2","c3","d4a5","e6e7","f8"
],dtype="string")

ser3

0      a1
1      b2
2      c3
3    d4a5
4    e6e7
5      f8
dtype: string

In [36]:
ser3.str.extractall(r"(\d)").groupby(level=0).agg("".join)

    0
0   1
1   2
2   3
3  45
4  67
5   8

In [40]:
ser3.str.extractall(r"([a-z])").groupby(level=0).agg("".join)

    0
0   a
1   b
2   c
3  da
4  ee
5   f

In [ ]:
# 숫자랑 필드랑 컬럼으로 분리

ser3.str.extract(r"(?P<letter>[a-z]+)(?P<Digit>\d+)")
# ser3.str.extract(r"(?P<letter>[a-z]+) (?P<Digit>\d+)") -> 띄우면 안됨.

  letter Digit
0      a     1
1      b     2
2      c     3
3      d     4
4      e     6
5      f     8